### ISSUE TITLE
Reusing allow="" is a bit weird

### ISSUE THREAD

**Issue by domenic** [bokand/page-collection#5]
allow="" already has a meaning related to permissions policy and `<iframe>`. Reusing it for `<a>`, presumably with a different set of tokens (not related to permissions policy), seems weird.

**Comment by bokand** [comment]
I'm trying to reuse as much as possible that already exists, this was meant to be analogous in terms of giving the link permission to perform some action "open multiple windows", but yeah, the tokens wouldn't be the same so point taken.

Taking another look at this...I see we can specify the content type for an anchor using the `type` attribute. We could restrict automatically opening multiple windows unless the link hints its type as `text/uri-list` (or whatever we decide on for the content type). Would that work?

**Comment by domenic** [comment]
Wow, fascinating, I'd totally forgotten `<a type="">` existed! Yeah, maybe it would work? Although changing something from a no-op "comment" to impacting the processing model is a bit unusual, so I think it would be worth some wider discussion.

In general, I think it's OK to invent new things for new features, instead of trying to find clever ways of reusing or repurposing existing things.

**Comment by bokand** [comment]
Having thought about it more, I take back `type` as a suggestion. In addition to what you said, `type` would only work if 'new tab group' remains the only such capability since it doesn't allow multiple types. If we ever wanted to say "allow this link to open new tab groups AND allow it to perform-some-new-action" we wouldn't be able to express that.

A new token for the `rel` attribute could work? I'm not sure `rel` is right for this since it's not really a relationship between the link and the current document but it feels somewhat similar to values like `noreferrer` or `noopener` in that it changes the processing model of invoking the link.

Another option is to add a boolean attribute: `<a collection href=...>`

+@vmpstr for thoughts as well.

Another thing to keep in mind is we'll likely also need this on `window.open`.
